# Generated by Django 5.1.6 on 2025-03-30 22:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_course_course_id'),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='text',
            new_name='choice_text',
        ),
        migrations.RemoveField(
            model_name='question',
            name='text',
        ),
        migrations.AddField(
            model_name='form',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.course'),
        ),
        migrations.AddField(
            model_name='form',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='form',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='form',
            name='teams',
            field=models.ManyToManyField(blank=True, to='courses.team'),
        ),
        migrations.AddField(
            model_name='form',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='question',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='question_text',
            field=models.CharField(default='Untitled Question', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='required',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('text', 'Text'), ('mcq', 'Multiple Choice'), ('likert', 'Likert')], max_length=10),
        ),
    ]
