# Generated by Django 5.1.6 on 2025-03-31 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_text_choice_choice_text_remove_question_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('text', 'Short Answer'), ('likert', 'Likert'), ('multiple_choice', 'Multiple Choice')], max_length=20),
        ),
    ]
