# Generated by Django 4.2.20 on 2025-04-15 04:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0004_alter_form_course_alter_form_teams_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='formresponse',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='form',
            name='allow_multiple_responses',
            field=models.BooleanField(default=False, help_text='Allow each student to submit one response per teammate'),
        ),
        migrations.AddField(
            model_name='formresponse',
            name='target_student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_responses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='formresponse',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_responses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='formresponse',
            unique_together={('form', 'student', 'target_student')},
        ),
    ]
